### ISSUE TITLE
EventbarCtrl seems to be running twice

### ISSUE THREAD

**Issue by mariusespejo** [librecms/librecms#108]
The controller for upcoming events seems to be running twice each time it gets used for a page

**Comment by mariusespejo** [comment]
@nbuhay do you know why this happens? Try adding a console.log to the if statement that calls getUserEvents() to see. I was changing the controller to load assignments too but I think this problem is messing it up

**Comment by nbuhay** [comment]
Off cuff I'm not sure, I'll look into it.  I think it has been doing this for a while now.

**Comment by zdwolfe** [comment]
@mbe5038 are you running up-to-date code?

**Comment by mariusespejo** [comment]
Yeah it was up to date when I noticed it

**Comment by zdwolfe** [comment]
@mbe5038  @nbuhay  is this still a problem? Close if it's not
