### ISSUE TITLE
Course Calendar Page Mockup

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#14]
- Mockup source (in my case I will be using Pencil to mock it up) in repo [here](https://github.com/librecms/librecms/tree/master/mockups)
- Description of behavior of page written in wiki
- Data models linked with page written in wiki
- Security considerations with page written in wiki
- Both instructor and Student view

**Comment by mariusespejo** [comment]
I added some additional mockups in the [wiki](https://github.com/librecms/librecms/wiki/Calendar). I might still edit them a bit, I'll upload the source soon.

**Comment by mariusespejo** [comment]
added more information to [wiki](https://github.com/librecms/librecms/wiki/Calendar#behavior)
