### ISSUE TITLE
Quiz / Exam Page (Student View) Mockup

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#15]
- Mockup source (in my case I will be using Pencil to mock it up) in repo [here](https://github.com/librecms/librecms/tree/master/mockups)
- Description of behavior of page written in wiki
- Data models linked with page written in wiki
- Security considerations with page written in wiki

**Comment by slb5427** [comment]
put stuff up on the wiki couldn't figure out how to upload mockups so I will attempt to do in class.
Also didn't understand what security concerns I should have put

**Comment by zdwolfe** [comment]
@slb5427 there's an icon to insert an image URL. You can upload it to Imgur
or something like that.

Security concerns I meant to consider who should be able to access the
page, when, etc.

Z
