### ISSUE TITLE
Dropbox still showing for a note

### ISSUE THREAD

**Issue by mjc0042** [librecms/librecms#32]
ng-show directive does not seem to be working

**Comment by zdwolfe** [comment]
@mjc0042 did you add `note.js` to `index.html`? I'm getting syntax error "missing" NoteCtrl.js controller:

```
Error: [ng:areq] Argument 'NoteCtrl' is not a function, got undefined
```

NoteCtrl is referenced in [app.js](https://github.com/librecms/librecms/commit/3dfb10d6b1663e610562dae6273ea1e59e1660ee#diff-74ee1925b95d78b5f45f5f9633a5401aR58) but never defined in [index.html](https://github.com/librecms/librecms/blob/3dfb10d6b1663e610562dae6273ea1e59e1660ee/src/angular/app/index.html#L51). So [the view](https://github.com/librecms/librecms/blob/content/src/angular/app/views/course.assignment.html#L18) is looking for `showSubmit` on it's scope but the controller is undefined, which makes `showSubmit` undefined.
