### ISSUE TITLE
Assignment List Description Box Styling

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#38]
Remove yellow border around textarea box.

![screenshot from 2013-11-01 13 34 39](https://f.cloud.github.com/assets/719730/1455607/e2b2a94a-431c-11e3-9714-92f5659ad80d.png)

**Comment by lumtiffany** [comment]
I don't see a yellow border. Do you still see it on your computer, Zach @zdwolfe?

**Comment by zdwolfe** [comment]
Yes
![screenshot from 2013-11-15 19 00 29](https://f.cloud.github.com/assets/719730/1554988/21f9544c-4e52-11e3-9b92-5fa56269fb84.png)

**Comment by jessgray** [comment]
Fixed it. Also added a margin because the box looked too high up.
