### ISSUE TITLE
Investigate "Gradebook" Feature

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#4]
Make a wiki page for and research the "Gradebook" features. Mock ups?

**Comment by zdwolfe** [comment]
@lumtiffany you mentioned you wanted to check this out too.

**Comment by nbuhay** [comment]
Note:  Add a class average thang.

**Comment by zdwolfe** [comment]
Javascript graphing library for graphing: http://www.chartjs.org/

**Comment by slb5427** [comment]
would like to implement multiple measurements for grade metrics that would be useful for instructors and students

**Comment by zdwolfe** [comment]
@slb5427 I like it. What metrics would you think are most important? I think Mean, Median, and Std. Deviation would be helpful to me as a student.
