### ISSUE TITLE
Investigate "Calendar" Feature

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#6]
Make a wiki page for and research the "Calendar" features. Click on "calendar" on the [features](https://github.com/opencms/opencms/wiki/Features) wiki page to add a wiki page for calendar. 

Mock ups would be awesome.

**Comment by zdwolfe** [comment]
@mbe5038  I really like [the mockup](https://github.com/librecms/librecms/wiki/Calendar/af08fb0a925367c4fbac71804f2e69a29ba4d787). What did you use to make it?

I think we should consolidate the "Event Creation" and [Assignment](https://github.com/librecms/librecms/wiki/Assignments/a21a1c3bd75dc22f88a8ac16e08e4646234cc41d) features to avoid feature duplication. Would you agree that instead of an "Assignment" being a subset of an "Event," that an Event and an Assignment should instead have a "has-a" relationship (foreign key relationship)?

I say that for the sake of flexibility. We might want to have Events that are not Assignments, but (arguably) all Assignments should have a corresponding Event. What do you think?

**Comment by mariusespejo** [comment]
@zdwolfe I used Pencil Project as well.

Yeah I agree all Assignments should definitely have corresponding Events and they should be linked. I was just thinking for Assignments it could be something that would be on a to-do list where you can cross it off once finished while certain events like an exam would be something that you would want to keep posted on the calendar. But we can definitely consolidate the Event Creation and Assignment features.

Also from my experience with a lot of classes instructors just end up making their own class calendars or they create a list of due dates. It would be nice if instructors would just input all those due dates in the calendar (we should probably have the option to make multiple events/assignments at once or a recurring event).

**Comment by zdwolfe** [comment]
@mbe5038 nice. I like the "to-do" list. Good idea! I agree that the UI should be very intuitive. Does your mockup reflect the creation of a list of due dates? We should work on that as a group this week. Nice work!

**Comment by mariusespejo** [comment]
I was thinking the list of assignments on the mockup that I made would be sorted by date and would basically be the list of due dates.

**Comment by mariusespejo** [comment]
@zdwolfe I'm still trying to get familiar with our stack but [this calendar](https://github.com/Serhioromano/bootstrap-calendar) might be something we can use?

**Comment by zdwolfe** [comment]
Great find. We should reuse and customize whatever we can. Do you know if it takes a requirement on Jquery?
