### ISSUE TITLE
Investigate "Assignments" Feature Edit

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#7]
Make a wiki page for and research the "Assignments" feature, including mockups.

**Comment by mariusespejo** [comment]
hey @zdwolfe I was just thinking shouldn't we have corresponding gradebook entries for every assignment as well? Or are we just making instructors create a gradebook entry after they've graded the assignment?

**Comment by zdwolfe** [comment]
@mbe5038 great point. Assignments and the Gradebook should be tightly integrated -- to the point that a "Gradebook entry" should be an "Assignment." What do you think?

**Comment by mariusespejo** [comment]
@zdwolfe We could have a checkbox that's checked by default saying "create a gradebook entry" or something (there might be assignments that aren't graded like read a chapter) and then if it's graded that "submit" button can be a continue button instead that goes to gradebook entries? Or it can just make the entry automatically

**Comment by zdwolfe** [comment]
@mbe5038

I like the check box idea.

I also think the expected behaviour would be to automatically create a
gradebook entry.

Also, I think the "creation" of a gradebook entry would instead be a flag
on an existing assignment.

Something like,  in Mongo:
Assignment = {
    "name": String,
    ...
    "graded": Boolean,
    ...
}

**Comment by slb5427** [comment]
just thought of a useful feature:
Allowing for submission to count for multiple students, allowing for student collaboration on certain assignments
