### ISSUE TITLE
User name color changes

### ISSUE THREAD

**Issue by zdwolfe** [librecms/librecms#85]
Because it's a link, when it's visited the color changes.
![screenshot from 2013-11-17 11 35 37](https://f.cloud.github.com/assets/719730/1558730/6d3cba7a-4fa6-11e3-8a81-83f5e5d441c6.png)

**Comment by zdwolfe** [comment]
@slb5427 is this fixed?

**Comment by slb5427** [comment]
I hadn't seen this until yesterday and it seemed to happen intermittently, so I'll look at it over break and see what I can do.
